const fakedata = [
  {
    name: 'Babu',
    salary: 350,
    level: 'expert',
    gender: 'male',
    age: 43,
    location: 'Dhaka',
    Available: true,
    img: 'http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Karina',
    salary: 550,
    level: 'expert',
    gender: 'female',
    age: 35,
    location: 'Khulna',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Ffreedesignfile.com%2Fupload%2F2017%2F05%2FSmiling-female-programmer-working-in-the-office-Stock-Photo-01.jpg&f=1&nofb=1',
  },
  {
    name: 'Solaiman',
    salary: 350,
    level: 'beginner',
    gender: 'male',
    age: 31,
    location: 'CTG',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fintermountainhealthcare.org%2F-%2Fmedia%2Fimages%2Fglobal%2F1-1%2Fmale-office-worker-smiling.jpg%3Fmw%3D1600&f=1&nofb=1',
  },
  {
    name: 'Jalal',
    salary: 550,
    level: 'medium',
    gender: 'male',
    age: 42,
    location: 'Barisal',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.wisegeek.com%2Fman-working-at-desk.jpg&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Rahim',
    salary: 350,
    level: 'expert',
    gender: 'male',
    age: 43,
    location: 'Dhaka',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fget.pxhere.com%2Fphoto%2Fwork-man-person-people-male-meeting-young-corporate-office-professional-business-profession-speaker-elder-job-meet-official-clergy-business-executive-businessperson-1079382.jpg&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Abdullah',
    salary: 250,
    level: 'expert',
    gender: 'male',
    age: 35,
    location: 'Khulna',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fenglish.cdn.zeenews.com%2Fsites%2Fdefault%2Ffiles%2F2015%2F07%2F24%2F383259-man-at-work-700.jpg&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Kalam',
    salary: 550,
    level: 'beginner',
    gender: 'male',
    age: 38,
    location: 'CTG',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fc.pxhere.com%2Fphotos%2F45%2F53%2Fbusinessman_man_portrait_male_costume_business_office_office_style-718631.jpg!d&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Mamun',
    salary: 1050,
    level: 'medium',
    gender: 'male',
    age: 42,
    location: 'Barisal',
    Available: true,
    img: 'hhttps://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fs-i.huffpost.com%2Fgen%2F1223196%2Fimages%2Fo-MEN-WORK-facebook.jpg&f=1&nofb=1ttp://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Kornel',
    salary: 300,
    level: 'expert',
    gender: 'male',
    age: 37,
    location: 'Jamalpur',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthumbs.dreamstime.com%2Fz%2Fman-office-portrait-male-worker-122153529.jpg&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Abida',
    salary: 800,
    level: 'expert',
    gender: 'female',
    age: 25,
    location: 'Rajshahi',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fdm0qx8t0i9gc9.cloudfront.net%2Fthumbnails%2Fvideo%2FVd3bj2jPe%2Fvideoblocks-smiling-business-woman-satisfied-successful-work-front-laptop-in-dark-office-portrait-of-happy-business-woman-looking-computer-monitor-in-night-office_swwocxe9gb_thumbnail-1080_07.png&f=1&nofb=1',
  },
  {
    name: 'Kasem',
    salary: 350,
    level: 'beginner',
    gender: 'male',
    age: 31,
    location: 'Gazipur',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthumbs.dreamstime.com%2Fz%2Fman-office-portrait-male-worker-122153529.jpg&f=1&nofb=1http://www.brightstudio.com.sg/images/Photography/Passport/Picture/passport13.jpg',
  },
  {
    name: 'Pia',
    salary: 750,
    level: 'medium',
    gender: 'female',
    age: 42,
    location: 'Pabna',
    Available: true,
    img: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg1.goodfon.com%2Fwallpaper%2Fnbig%2F4%2F66%2Fdevushka-litso-volosy-vzgliad-ulybka-sekretarsha-kabinet.jpg&f=1&nofb=1',
  },
];
